- hosts: all
  become: true
  tasks:
    - name: Installation of GIT
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_os_family== "RedHat"

    - name: installation of Jenkins
      ansible.builtin.apt:
        name: git
        state: present
      when: ansible_os_family== "Debian"
